<a href="https://colab.research.google.com/github/ray-dion/TC3/blob/main/TC3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# import lib

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

from datetime import datetime

# Data Load

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/FTDS-learning-materials/phase-1/refs/heads/master/w3/P1W3D5AM%20-%20Technical%20Test%203%20-%20ML%20Data%20Preparation%20-%20Transactions.csv')
df

,transaction_id,user_id,transaction_amount,transaction_date,merchant_id,merchant_name,merchant_category_id,geo_location,payment_method,user_agent,loyalty_program,discount_applied,promo_amount,transaction_notes,merchant_rating,transaction_status,is_refunded
0,4a71b7d1-34fa-45cf-b40a-a730d16ce617,U10578,23500.0,2024-05-09,M04936,Cox Inc,5732,"-7.974781, 112.633863",balance,Android 9,no,no,0.0,no,5,completed,no
1,b29665c0-8373-4ec1-a121-a041c77ffb51,U08353,150500.0,2024-05-30,M06359,"King, Rice and Ramirez",5812,"-6.188155, 106.817086",balance,iPhone; CPU iPhone OS 3_1_3 like Mac OS X,no,no,0.0,yes,2,completed,no
2,3e32187b-b374-4f1b-a64e-b1ebcc856563,U04564,65800.0,2024-03-08,M01710,"Lyons, Porter and Williams",5812,"-7.962043, 112.637274",credit_card,Android 2.0.1,no,no,0.0,no,3,completed,no
3,df8ad42e-aaf6-46d2-8d8f-1e291a4554bd,U22797,45600.0,2024-05-14,M02852,Smith Ltd,5411,"-6.592793, 106.806543",balance,iPad; CPU iPad OS 9_3_5 like Mac OS X,no,no,0.0,no,3,completed,no
4,334468df-4d71-4e4a-935c-32c17c306611,U18053,8500.0,2024-04-09,M00722,Bush Group,5411,"-6.269386, 106.979043",balance,Android 2.0.1,yes,no,0.0,no,4,completed,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
278927,77e14f67-1672-4199-96de-b51628e79513,U13928,35300.0,2024-05-15,M05011,White Inc,5812,"-6.205038, 106.830156",balance,iPad; CPU iPad OS 2_2_1 like Mac OS X,yes,yes,11100.0,no,3,completed,no
278928,22d95830-2c41-4b3a-9a12-bde3d28a86a0,U22337,30400.0,2024-05-01,M03137,Martinez-Bentley,5812,"-6.597706, 106.798488",credit_card,iPad; CPU iPad OS 17_3_1 like Mac OS X,no,yes,8200.0,yes,4,completed,no
278929,f12b9af5-d3e5-48d5-98e6-1c0649cf20ad,U08210,22700.0,2024-04-15,M03544,Scott Inc,5541,"-7.868800, 110.427310",balance,iPad; CPU iPad OS 9_3_6 like Mac OS X,no,no,0.0,no,3,completed,no
278930,2648fd0d-e071-4dac-9852-7b367c6876ae,U17161,43100.0,2024-05-11,M01689,"Young, Johnston and Williams",7994,"-6.199598, 106.822475",balance,iPad; CPU iPad OS 17_1_2 like Mac OS X,no,no,0.0,no,3,completed,no
278931,61c76cf6-dbf0-4f9e-beee-8476f3b8fc0d,U10311,6900.0,2024-05-10,M00288,Lowe-Perry,5411,"-6.195206, 106.821896",balance,Android 4.3,yes,no,0.0,no,5,completed,no

# Data Exploration & Data Vis

In [3]:
# Check data types

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278932 entries, 0 to 278931
Data columns (total 17 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   transaction_id        278932 non-null  object
 1   user_id               278932 non-null  object
 2   transaction_amount    278932 non-null  float64
 3   transaction_date      278932 non-null  object
 4   merchant_id           278932 non-null  object
 5   merchant_name         278932 non-null  object
 6   merchant_category_id  278932 non-null  int64
 7   geo_location          278932 non-null  object
 8   payment_method        278932 non-null  object
 9   user_agent            278932 non-null  object
 10  loyalty_program       278932 non-null  object
 11  discount_applied      278932 non-null  object
 12  promo_amount          278932 non-null  float64
 13  transaction_notes     278932 non-null  object
 14  merchant_rating       278932 non-null  int64
 15  transaction_status    278932 non-null  object
 16  is_refunded           278932 non-null  object
dtypes: float64(2), int64(2), object(13)
memory usage: 36.2+ MB

In [4]:
# Check Null

df.isnull().sum()

transaction_id          0
user_id                 0
transaction_amount      0
transaction_date        0
merchant_id             0
merchant_name           0
merchant_category_id    0
geo_location            0
payment_method          0
user_agent              0
loyalty_program         0
discount_applied        0
promo_amount            0
transaction_notes       0
merchant_rating         0
transaction_status      0
is_refunded             0
dtype: int64

In [5]:
# Summary Check

df.describe()

,transaction_amount,merchant_category_id,promo_amount,merchant_rating
count,278932.000000,278932.000000,278932.000000,278932.00000
mean,50098.301378,5806.529964,4311.858087,3.80046
std,50021.138491,509.152141,16527.140346,1.16671
min,1000.000000,4722.000000,0.000000,1.00000
25%,14400.000000,5541.000000,0.000000,3.00000
50%,34800.000000,5812.000000,0.000000,4.00000
75%,69400.000000,5912.000000,0.000000,5.00000
max,587100.000000,8220.000000,422600.000000,5.00000

Melihat nilai mean dengan median secara sekilas:
1. transaction_amount distribusi skewed ke kanan. Beberapa transaksi tergolong sangat tinggi dibanding dengan mayoritas transaksi lainnya.
2. promo_amount distribusi skewed kanan juga. Tetapi melihat nilai seluruh kuartil maka dapat dilihat bahwa penggunaan promo jarang digunakan.

In [7]:
# Summary check for cat column

df.describe(include=['O']).T

,count,unique,top,freq
transaction_id,278932,278932,4a71b7d1-34fa-45cf-b40a-a730d16ce617,1
user_id,278932,24321,U07052,27
transaction_date,278932,92,2024-04-07,6854
merchant_id,278932,6489,M02610,70
merchant_name,278932,5820,Johnson Group,657
geo_location,278932,278916,"-7.967859, 112.631819",2
payment_method,278932,2,balance,222978
user_agent,278932,136,Android 3.2.1,3214
loyalty_program,278932,2,no,211974
discount_applied,278932,2,no,231340
transaction_notes,278932,2,no,214887
transaction_status,278932,2,completed,264907
is_refunded,278932,2,no,264821

- High Cardinality menghasilkan model yang cenderung overfit karena model lebih menghafal dan bukan mempelajari pola yang ada. Maka dari itu kolom seperti transaction_id, user_id, merchant_id, merchant_name, geo_location, dan user_agent perlu dikurangi kardinalitasnya atau tidak diikutkan pada feature selection

In [8]:
# Data validation

df['transaction_date'] = pd.to_datetime(df['transaction_date'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278932 entries, 0 to 278931
Data columns (total 17 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   transaction_id        278932 non-null  object
 1   user_id               278932 non-null  object
 2   transaction_amount    278932 non-null  float64
 3   transaction_date      278932 non-null  datetime64[ns]
 4   merchant_id           278932 non-null  object
 5   merchant_name         278932 non-null  object
 6   merchant_category_id  278932 non-null  int64
 7   geo_location          278932 non-null  object
 8   payment_method        278932 non-null  object
 9   user_agent            278932 non-null  object
 10  loyalty_program       278932 non-null  object
 11  discount_applied      278932 non-null  object
 12  promo_amount          278932 non-null  float64
 13  transaction_notes     278932 non-null  object
 14  merchant_rating       278932 non-null  int64
 15  transaction_status    278932 non-null  object
 16  is_refunded           278932 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(2), object(12)
memory usage: 36.2+ MB

In [9]:
# Range checks

negative = df[df['transaction_amount']<0]
if not negative.empty:
  print(negative)

negative_promo = df[df['promo_amount']<0]
if not negative_promo.empty:
  print(negative_promo)

invalid_merchant_rating = df[(df['merchant_rating']<0) | (df['merchant_rating']>5)]
if not invalid_merchant_rating.empty:
  print(invalid_merchant_rating)

In [10]:
# improbable promo

improbable_promo = df[df['promo_amount']>df['transaction_amount']]
if not improbable_promo.empty:
  print(improbable_promo)

In [11]:
# Check duplicate

df.duplicated().sum()

0

# FE (FC)

In [12]:
# Cardinality Check

df.nunique()

transaction_id          278932
user_id                  24321
transaction_amount        3439
transaction_date            92
merchant_id               6489
merchant_name             5820
merchant_category_id        21
geo_location            278916
payment_method               2
user_agent                 136
loyalty_program              2
discount_applied             2
promo_amount              1850
transaction_notes            2
merchant_rating              5
transaction_status           2
is_refunded                  2
dtype: int64

In [14]:
# Column with high cardinality

high_cardinality = df[['transaction_id', 'user_id', 'merchant_id', 'merchant_name', 'geo_location', 'user_agent']]

for col in high_cardinality.columns:
  print(f'Column {col}: ')
  print(f'{df[col].unique()}\n')

Column transaction_id:
['4a71b7d1-34fa-45cf-b40a-a730d16ce617'
 'b29665c0-8373-4ec1-a121-a041c77ffb51'
 '3e32187b-b374-4f1b-a64e-b1ebcc856563' ...
 'f12b9af5-d3e5-48d5-98e6-1c0649cf20ad'
 '2648fd0d-e071-4dac-9852-7b367c6876ae'
 '61c76cf6-dbf0-4f9e-beee-8476f3b8fc0d']

Column user_id:
['U10578' 'U08353' 'U04564' ... 'U13010' 'U05019' 'U08058']

Column merchant_id:
['M04936' 'M06359' 'M01710' ... 'M04490' 'M02608' 'M06365']

Column merchant_name:
['Cox Inc' 'King, Rice and Ramirez' 'Lyons, Porter and Williams' ...
 'Luna Group' 'Green, Chambers and Roberts' 'Green PLC']

Column geo_location:
['-7.974781, 112.633863' '-6.188155, 106.817086' '-7.962043, 112.637274'
 ... '-7.868800, 110.427310' '-6.199598, 106.822475'
 '-6.195206, 106.821896']

Column user_agent:
['Android 9' 'iPhone; CPU iPhone OS 3_1_3 like Mac OS X' 'Android 2.0.1'
 'iPad; CPU iPad OS 9_3_5 like Mac OS X' 'Android 3.2.2' 'Android 4.4.3'
 'Android 5.0.1' 'Android 11' 'iPad; CPU iPad OS 7_1_2 like Mac OS X'
 'Android 7.1.1' 'Android 3.2.3' 'Android 4.0.1' 'Android 13'
 'Android 4.4.4' 'Android 3.2.4' 'Android 4.1' 'Android 7.0'
 'Android 7.1.2' 'Android 8.1.0'
 'iPhone; CPU iPhone OS 13_5_1 like Mac OS X'
 'iPhone; CPU iPhone OS 17_2_1 like Mac OS X'
 'iPhone; CPU iPhone OS 14_2 like Mac OS X'
 'iPhone; CPU iPhone OS 2_2_1 like Mac OS X'
 'iPad; CPU iPad OS 14_2_1 like Mac OS X' 'Android 4.0.2' 'Android 4.2'
 'Android 12.1' 'Android 1.5' 'Android 4.0.4' 'Android 6.0.1'
 'Android 3.2.5' 'iPhone; CPU iPhone OS 16_7_6 like Mac OS X'
 'Android 2.3.4' 'Android 8.0.0' 'Android 2.3.1'
 'iPad; CPU iPad OS 10_3_3 like Mac OS X' 'Android 5.0' 'Android 2.1'
 'Android 2.2.1' 'Android 1.6' 'Android 2.2' 'Android 7.1' 'Android 2.3.2'
 'Android 2.3.6' 'Android 4.1.1' 'Android 4.0' 'Android 14' 'Android 4.4'
 'Android 5.1' 'Android 12' 'iPad; CPU iPad OS 1_1_5 like Mac OS X'
 'iPhone; CPU iPhone OS 12_4_8 like Mac OS X' 'Android 2.2.2'
 'iPhone; CPU iPhone OS 17_1 like Mac OS X'
 'iPad; CPU iPad OS 10_3_4 like Mac OS X'
 'iPhone; CPU iPhone OS 14_8_1 like Mac OS X'
 'iPhone; CPU iPhone OS 3_2_2 like Mac OS X'
 'iPhone; CPU iPhone OS 6_1_6 like Mac OS X'
 'iPhone; CPU iPhone OS 17_4 like Mac OS X' 'Android 2.2.3'
 'Android 5.1.1' 'iPad; CPU iPad OS 16_7_7 like Mac OS X'
 'iPhone; CPU iPhone OS 17_3 like Mac OS X'
 'iPad; CPU iPad OS 17_3 like Mac OS X' 'Android 3.2.6' 'Android 4.3.1'
 'iPhone; CPU iPhone OS 7_1_2 like Mac OS X' 'Android 2.3.3'
 'iPad; CPU iPad OS 3_1_3 like Mac OS X'
 'iPad; CPU iPad OS 13_7 like Mac OS X'
 'iPad; CPU iPad OS 12_4_4 like Mac OS X'
 'iPad; CPU iPad OS 3_2_2 like Mac OS X' 'Android 6.0'
 'iPhone; CPU iPhone OS 4_2_1 like Mac OS X'
 'iPad; CPU iPad OS 4_2_1 like Mac OS X' 'Android 5.0.2'
 'iPhone; CPU iPhone OS 10_3_4 like Mac OS X'
 'iPhone; CPU iPhone OS 10_3_3 like Mac OS X'
 'iPad; CPU iPad OS 14_2 like Mac OS X'
 'iPad; CPU iPad OS 17_1 like Mac OS X'
 'iPad; CPU iPad OS 12_5_7 like Mac OS X'
 'iPhone; CPU iPhone OS 17_1_1 like Mac OS X'
 'iPhone; CPU iPhone OS 1_1_5 like Mac OS X'
 'iPad; CPU iPad OS 17_2_1 like Mac OS X' 'Android 2.3.5'
 'iPad; CPU iPad OS 9_3_6 like Mac OS X'
 'iPad; CPU iPad OS 15_8_2 like Mac OS X'
 'iPhone; CPU iPhone OS 11_4_1 like Mac OS X' 'Android 4.3'
 'Android 2.3.7' 'Android 1.1' 'iPad; CPU iPad OS 16_7_6 like Mac OS X'
 'iPad; CPU iPad OS 17_1_2 like Mac OS X' 'Android 2.3' 'Android 4.2.1'
 'iPhone; CPU iPhone OS 16_7_7 like Mac OS X'
 'iPad; CPU iPad OS 17_3_1 like Mac OS X' 'Android 4.4.2' 'Android 4.1.2'
 'iPad; CPU iPad OS 8_4_1 like Mac OS X' 'Android 3.2' 'Android 3.2.1'
 'iPhone; CPU iPhone OS 15_8_2 like Mac OS X'
 'iPhone; CPU iPhone OS 9_3_6 like Mac OS X' 'Android 2.0' 'Android 4.2.2'
 'Android 4.4.1' 'iPhone; CPU iPhone OS 12_5_7 like Mac OS X'
 'iPad; CPU iPad OS 17_2 like Mac OS X' 'Android 10'
 'iPhone; CPU iPhone OS 13_7 like Mac OS X'
 'iPad; CPU iPad OS 13_5_1 like Mac OS X'
 'iPhone; CPU iPhone OS 17_3_1 like Mac OS X'
 'iPad; CPU iPad OS 17_4_1 like Mac OS X'
 'iPhone; CPU iPhone OS 17_4_1 like Mac OS X' 'Android 3.0'
 'iPad; CPU iPad OS 17_1_1 like Mac OS X' 'Android 3.1'
 'iPad; CPU iPad OS 11_4_1 like Mac OS X'
 'iPhone; CPU iPhone OS 17_2 like Mac OS X'
 'iPhone; CPU iPhone OS 4_3_5 like Mac OS X' 'Android 4.0.3'
 'iPad; CPU iPad OS 2_2_1 like Mac OS X'
 'iPad; CPU iPad OS 14_8_1 like Mac OS X'
 'iPad; CPU iPad OS 12_4_8 like Mac OS X'
 'iPad; CPU iPad OS 6_1_6 like Mac OS X'
 'iPhone; CPU iPhone OS 9_3_5 like Mac OS X' 'Android 1.0'
 'iPhone; CPU iPhone OS 8_4_1 like Mac OS X'
 'iPhone; CPU iPhone OS 5_1_1 like Mac OS X'
 'iPhone; CPU iPhone OS 17_1_2 like Mac OS X'
 'iPad; CPU iPad OS 4_3_5 like Mac OS X'
 'iPad; CPU iPad OS 17_4 like Mac OS X'
 'iPhone; CPU iPhone OS 12_4_4 like Mac OS X'
 'iPad; CPU iPad OS 5_1_1 like Mac OS X'
 'iPhone; CPU iPhone OS 14_2_1 like Mac OS X']

## FC Handling Cardinality